<a href="https://colab.research.google.com/github/AkshayKulkarni1904/Python/blob/main/Python_Day_20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#***Numpy***
what is numpy?

what is its baground data type?


### Importing NumPy
Before using NumPy, it's a standard practice to import the library, usually aliased as `np` for convenience.

In [1]:
import numpy as np

### Creating a 1D Array
A 1-dimensional array, often referred to as a vector, can be created from a Python list using `np.array()`.

In [2]:
#1D array

a=np.array([20,10,99,40,100])
a

array([ 20,  10,  99,  40, 100])

### Checking NumPy Version
You can check the installed version of NumPy using `np.__version__`.

In [3]:
np.__version__

'2.0.2'

### Finding the Maximum Value
The `max()` method returns the largest element in the array.

In [4]:
#Find max / largest number
a.max()    #np.int64(100) its shown as we are using nootbook

np.int64(100)

### Finding the Minimum Value
The `min()` method returns the smallest element in the array.

In [5]:
a.min()

np.int64(10)

### Checking the Number of Elements
The `size` attribute returns the total number of elements in the array.

In [6]:
#To show elements present (part of debuging)
a.size

5

### Checking the Number of Dimensions
The `ndim` attribute returns the number of dimensions of the array.

In [7]:
#dimension
a.ndim

1

### Checking the Data Type of the Array Object
The `type()` function in Python can be used to determine the type of the NumPy array object.

In [8]:
type(a)

numpy.ndarray

### Creating a 2D Array
A 2-dimensional array, often referred to as a matrix, can be created from a list of lists using `np.array()`.

In [9]:
#Q.What is a type of Numpy array?

In [10]:
b=np.array([[10,20,1],
           [-1,5,9],
           [7,40,2]])
b

array([[10, 20,  1],
       [-1,  5,  9],
       [ 7, 40,  2]])

### Checking Dimensions for a 2D Array
For a 2D array, `ndim` will return 2.

In [11]:
b.ndim

2

### Checking the Shape of a 2D Array
The `shape` attribute returns a tuple indicating the size of each dimension (rows, columns).

In [12]:
#To check number of row and coloums
b.shape #(row,coloumn)

(3, 3)

### Sum of all Elements in an Array
The `sum()` method without an `axis` argument calculates the sum of all elements in the array.

In [13]:
#addition of all elements in array
print(b.sum())

93


### Column-wise Addition
Using `axis=0` in the `sum()` method calculates the sum along the columns.

In [14]:
#coloumnwise addition
print(b.sum(axis=0))

[16 65 12]


### Row-wise Addition
Using `axis=1` in the `sum()` method calculates the sum along the rows.

In [15]:
#row addition
print(b.sum(axis=1))

[31 13 49]


### Assignment Solutions
Let's perform the requested operations (`min()`, `max()`, `mean()`, `std()`) on array `b`.

In [16]:
# Create a 1D array for slicing example
arr_1d = np.arange(0, 10)
print('Original 1D array:', arr_1d)

# Slice from index 2 up to (but not including) index 7
print('Slice (2:7):', arr_1d[2:7])

# Slice from the beginning to index 5
print('Slice (:5):', arr_1d[:5])

# Slice from index 3 to the end
print('Slice (3:):', arr_1d[3:])

# Slice with a step (every second element)
print('Slice with step (::2):', arr_1d[::2])

# Slice in reverse order
print('Reverse slice (::-1):', arr_1d[::-1])

# Create a 2D array for slicing example
arr_2d = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])
print('\nOriginal 2D array:\n', arr_2d)

# Slice rows and columns
# Get the first two rows and all columns
print('First two rows (arr_2d[:2, :]):\n', arr_2d[:2, :])

# Get all rows and the last two columns
print('Last two columns (arr_2d[:, 2:]):\n', arr_2d[:, 2:])

# Get specific rows and columns
# Get row 1 and columns from index 1 to 3
print('Row 1, cols 1-3 (arr_2d[1, 1:4]):', arr_2d[1, 1:4])

# Get rows 0 and 2, and columns 0 and 2
print('Specific rows and columns (arr_2d[[0, 2], [0, 2]]):', arr_2d[[0, 2], [0, 2]])

# Slicing with step in 2D
# Every other row, all columns
print('Every other row (arr_2d[::2, :]):\n', arr_2d[::2, :])

Original 1D array: [0 1 2 3 4 5 6 7 8 9]
Slice (2:7): [2 3 4 5 6]
Slice (:5): [0 1 2 3 4]
Slice (3:): [3 4 5 6 7 8 9]
Slice with step (::2): [0 2 4 6 8]
Reverse slice (::-1): [9 8 7 6 5 4 3 2 1 0]

Original 2D array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
First two rows (arr_2d[:2, :]):
 [[1 2 3 4]
 [5 6 7 8]]
Last two columns (arr_2d[:, 2:]):
 [[ 3  4]
 [ 7  8]
 [11 12]]
Row 1, cols 1-3 (arr_2d[1, 1:4]): [6 7 8]
Specific rows and columns (arr_2d[[0, 2], [0, 2]]): [ 1 11]
Every other row (arr_2d[::2, :]):
 [[ 1  2  3  4]
 [ 9 10 11 12]]


#### Find the minimum value of array `b`

In [17]:
print(b.min())

-1


#### Find the maximum value of array `b`

In [18]:
print(b.max())

40


#### Find the mean of all elements in array `b`

In [19]:
print(b.mean())

10.333333333333334


#### Find the standard deviation of all elements in array `b`

In [20]:
print(b.std())

12.01850425154663


###***Diffrent ways to creat numpy array***

### Creating NumPy arrays with random numbers
The `np.random.random()` function generates an array of specified shape populated with random floats in the half-open interval `[0.0, 1.0)`.

In [21]:
#numpy array with random numbers
np.random.random(5)


array([0.58383484, 0.02904501, 0.84801383, 0.35303235, 0.39663619])

### Creating a 2D array with random numbers
You can specify the dimensions as a tuple for a multi-dimensional array.

In [22]:
np.random.random((5,3))

array([[0.89580529, 0.68705492, 0.84083242],
       [0.76828473, 0.00705335, 0.5474458 ],
       [0.81985529, 0.09420101, 0.59699781],
       [0.94689859, 0.96343966, 0.26703234],
       [0.33965118, 0.87985916, 0.70315659]])

### Creating a 3D array with random numbers
NumPy can create arrays of arbitrary dimensions, here's a 3D example (blocks, rows, columns).

In [23]:
#3d(block,row,cloumn)
#array is one of the faster data type
np.random.random((2,2,2))

array([[[0.95511687, 0.50631284],
        [0.99926279, 0.22333854]],

       [[0.32169948, 0.52838591],
        [0.34456201, 0.23521855]]])

### Generating a sequence of numbers with `np.arange()`
The `np.arange()` function creates an array with evenly spaced values within a given interval, similar to Python's built-in `range()` but returning a NumPy array.

In [24]:
#genate array with sequence of numbers
c=np.arange(24)
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

### Reshaping an array (temporary)
The `reshape()` method changes the shape of an array without changing its data. It returns a *new* array with the specified shape, leaving the original array unchanged.

In [25]:
c.size

24

In [26]:
#Convert from 1d to 2d (Interview question)
#resize / reshape (temperory / permanent)
#6x4,8x3,12x2,1x24
c.reshape((2,12))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

### Verifying `reshape()` is temporary
As seen, the original array `c` remains in its 1D form after `reshape()`.

In [27]:
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

### Resizing an array (permanent)
The `resize()` method changes the shape of an array *in-place*, meaning it modifies the original array. If the new shape requires more elements than the original, it fills with zeros by default. If it requires fewer, it truncates.

In [28]:
c.resize((3,8))

### Verifying `resize()` is permanent
After `resize()`, the array `c` has permanently changed its shape.

In [29]:
c

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

### Checking the new shape
`c.shape` now reflects the permanently resized dimensions.

In [30]:
c.shape

(3, 8)

### Flattening an array with `ravel()`
The `ravel()` method returns a flattened 1D array. Like `reshape()`, it produces a *view* if possible, or a copy if necessary, but does not modify the original array in-place.

In [31]:
#convert nD to 1D----> use ravel()--->(temperory)
c.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

### Basic Indexing: Accessing elements in a 1D array
NumPy arrays support both positive and negative indexing, similar to Python lists. Negative indices count from the end of the array.

###**Basic Indexing**

### Accessing elements in a 2D array
For 2D arrays, indexing typically uses `[row_index, column_index]`.

In [32]:
x=np.arange(10)
x[-2]

np.int64(8)

In [33]:
x[4]

np.int64(4)

Let's reshape `x` into a 2D array first to demonstrate 2D indexing.

In [34]:
x = x.reshape((2,5))
x[1,3]

np.int64(8)

### Slicing and Striding Examples
Slicing allows you to extract subarrays or parts of an array. It uses the `start:stop:step` notation.

Let's create a 1D array and a 2D array to demonstrate slicing and striding.

###***Slicing and Striding***

Basic slicing extends Python’s basic concept of slicing to N dimensions. Basic slicing occurs when obj is a `slice` object (constructed by start:stop:step notation inside of brackets), an integer, or a tuple of slice objects and integers. `Ellipsis` and `newaxis` objects can be interspersed with these as well.

